[build]
  command = "npm run build"
  publish = "dist"


[[redirects]]
  from = "/api-cocktails/*"
  to = "https://cocktailsapi-9qny.onrender.com/:splat"
  status = 200
  force = true

# Redirección para React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200